kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "shinobi.fullname" . }}-pv-claim
  labels:
    {{- include "shinobi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi